FROM debian
RUN apt-get update \
&& apt-get install --no-install-recommends -y \
	$([ "$(dpkg --print-architecture)" != amd64 ] && echo crossbuild-essential-amd64 || echo) \
	bc \
	bison \
	bsdextrautils \
	build-essential \
	ca-certificates \
	cpio \
	curl \
	fdisk \
	flex \
	gawk \
	gdb-multiarch \
	git \
	jq \
	libelf-dev \
	libssl-dev \
	mtools \
	nasm \
	python3 \
	python3-pefile \
	qemu-system-x86 \
	vim \
	xz-utils \
&& curl -sSLf https://github.com/systemd/systemd/raw/refs/heads/main/src/ukify/ukify.py > /usr/local/bin/ukify && chmod +x /usr/local/bin/ukify
